// <auto-generated />
using LaMiaPizzeriaEfPost.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaMiaPizzeriaEfPost.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20230110143918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaMiaPizzeriaEfPost.Models.Pizza", b =>
                {
                    b.Property<string>("nome")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("descrizione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("foto")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<double>("prezzo")
                        .HasColumnType("float");

                    b.HasKey("nome");

                    b.ToTable("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
